[project]
name = "bridgarr3"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.bridgarr]
path = "contracts/bridgarr.clar"
depends_on = []

[contracts.counter]
path = "contracts/counter.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
